"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-06-11 21:38:05.391684
"""

from __future__ import annotations

from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("actor_seq", sa.Integer(), nullable=False),
        sa.Column("visibility", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("hosting_mode", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("retention_policy", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("actor_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("object_ref", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("before", sa.JSON(), nullable=True),
        sa.Column("after", sa.JSON(), nullable=True),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("chain_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_events_actor_id"), ["actor_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_events_object_ref"), ["object_ref"], unique=False
        )

    op.create_table(
        "schema_version",
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("revision", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("applied_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("version"),
    )
    op.create_table(
        "workspaces",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("actor_seq", sa.Integer(), nullable=False),
        sa.Column("visibility", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("hosting_mode", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("retention_policy", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "members",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("actor_seq", sa.Integer(), nullable=False),
        sa.Column("visibility", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("hosting_mode", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("retention_policy", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("workspace_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_members_email"), ["email"], unique=False)
        batch_op.create_index(batch_op.f("ix_members_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "projects",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("actor_seq", sa.Integer(), nullable=False),
        sa.Column("visibility", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("hosting_mode", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("retention_policy", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("workspace_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("goal", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("scope", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("owner", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("target_date", sa.DateTime(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_projects_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "tickets",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("actor_seq", sa.Integer(), nullable=False),
        sa.Column("visibility", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("hosting_mode", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("retention_policy", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("priority", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column("assignee", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("due_date", sa.DateTime(), nullable=True),
        sa.Column("acceptance_criteria", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("lifecycle_stage", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("parent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["tickets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tickets_parent_id"), ["parent_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tickets_project_id"), ["project_id"], unique=False)

    op.create_table(
        "tokens",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("actor_seq", sa.Integer(), nullable=False),
        sa.Column("visibility", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("hosting_mode", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("retention_policy", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("member_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hashed", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("scopes", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tokens_member_id"), ["member_id"], unique=False)

    op.create_table(
        "agent_proposals",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("actor_seq", sa.Integer(), nullable=False),
        sa.Column("visibility", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("hosting_mode", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("retention_policy", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("ticket_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("proposer_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("diff", sa.JSON(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("agent_proposals", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_agent_proposals_ticket_id"), ["ticket_id"], unique=False
        )

    op.create_table(
        "comments",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("actor_seq", sa.Integer(), nullable=False),
        sa.Column("visibility", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("hosting_mode", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("retention_policy", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("ticket_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("author_actor_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("body", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["tickets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_comments_ticket_id"), ["ticket_id"], unique=False)

    # ### end Alembic commands ###

    # Stamp the schema version so the runtime guard (FR-E02-4) has a row to read.
    op.bulk_insert(
        sa.table(
            "schema_version",
            sa.column("version", sa.Integer),
            sa.column("revision", sa.String),
            sa.column("applied_at", sa.DateTime),
        ),
        [{"version": 1, "revision": "0001", "applied_at": datetime.now(UTC)}],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_comments_ticket_id"))

    op.drop_table("comments")
    with op.batch_alter_table("agent_proposals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_proposals_ticket_id"))

    op.drop_table("agent_proposals")
    with op.batch_alter_table("tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tokens_member_id"))

    op.drop_table("tokens")
    with op.batch_alter_table("tickets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tickets_project_id"))
        batch_op.drop_index(batch_op.f("ix_tickets_parent_id"))

    op.drop_table("tickets")
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_projects_workspace_id"))

    op.drop_table("projects")
    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_members_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_members_email"))

    op.drop_table("members")
    op.drop_table("workspaces")
    op.drop_table("schema_version")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_object_ref"))
        batch_op.drop_index(batch_op.f("ix_audit_events_actor_id"))

    op.drop_table("audit_events")
    # ### end Alembic commands ###
