"""Crypto-profile golden-vector loaders (MOD-30, D-11 / FR-E03-6).

Two checked-in fixture files under ``packages/test_harness/fixtures``:

- ``protocol_golden_vectors.json`` — kantaq events and grants with their
  canonical signing bytes and Ed25519 signatures, generated by
  ``scripts/gen_protocol_vectors.py`` with pyca/cryptography and
  cross-verified with PyNaCl at generation time.
- ``rfc8032_vectors.json`` — the RFC 8032 §7.1 Ed25519 vectors, grounding
  the primitive in the standard's own test data.

Loaded per-test (never on the pytest plugin path — the MOD-30 coverage rule).
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

_FIXTURES = Path(__file__).resolve().parents[2] / "fixtures"
PROTOCOL_VECTORS_PATH = _FIXTURES / "protocol_golden_vectors.json"
RFC8032_VECTORS_PATH = _FIXTURES / "rfc8032_vectors.json"


@dataclass(frozen=True, slots=True)
class SignatureVector:
    """One signed message: who signed what, and the expected signature."""

    name: str
    private_key_hex: str
    public_key_hex: str
    message_hex: str
    sig_hex: str


@dataclass(frozen=True, slots=True)
class EntityVector:
    """One golden kantaq entity (event or grant) plus its signature vector."""

    name: str
    entity: dict[str, Any]
    private_key_hex: str
    public_key_hex: str
    signing_bytes_hex: str
    sig_hex: str


def load_rfc8032_vectors(path: Path | None = None) -> tuple[SignatureVector, ...]:
    raw = json.loads((path or RFC8032_VECTORS_PATH).read_text())
    vectors = tuple(
        SignatureVector(
            name=entry["name"],
            private_key_hex=entry["private_key_hex"],
            public_key_hex=entry["public_key_hex"],
            message_hex=entry["message_hex"],
            sig_hex=entry["sig_hex"],
        )
        for entry in raw["vectors"]
    )
    if not vectors:
        raise ValueError(f"empty RFC 8032 vector file: {path or RFC8032_VECTORS_PATH}")
    return vectors


def _entity_vectors(raw_entries: list[dict[str, Any]], key: str) -> tuple[EntityVector, ...]:
    return tuple(
        EntityVector(
            name=entry["name"],
            entity=entry[key],
            private_key_hex=entry["private_key_hex"],
            public_key_hex=entry["public_key_hex"],
            signing_bytes_hex=entry["signing_bytes_hex"],
            sig_hex=entry["sig_hex"],
        )
        for entry in raw_entries
    )


def load_protocol_vectors(
    path: Path | None = None,
) -> tuple[tuple[EntityVector, ...], tuple[EntityVector, ...]]:
    """Returns ``(event_vectors, grant_vectors)`` from the golden file."""
    raw = json.loads((path or PROTOCOL_VECTORS_PATH).read_text())
    events = _entity_vectors(raw["events"], "event")
    grants = _entity_vectors(raw["grants"], "grant")
    if not events or not grants:
        raise ValueError(f"golden vector file is incomplete: {path or PROTOCOL_VECTORS_PATH}")
    return events, grants
