"""Crypto-profile golden-vector loaders (MOD-30, D-11 / FR-E03-6).

Two checked-in fixture files under ``packages/test_harness/fixtures``:

- ``protocol_golden_vectors.json`` — kantaq events and grants with their
  canonical signing bytes and Ed25519 signatures, generated by
  ``scripts/gen_protocol_vectors.py`` with pyca/cryptography and
  cross-verified with PyNaCl at generation time.
- ``rfc8032_vectors.json`` — the RFC 8032 §7.1 Ed25519 vectors, grounding
  the primitive in the standard's own test data.

Loaded per-test (never on the pytest plugin path — the MOD-30 coverage rule).
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from kantaq_protocol import Event
from kantaq_sync_engine.events import CommittedEvent

_FIXTURES = Path(__file__).resolve().parents[2] / "fixtures"
PROTOCOL_VECTORS_PATH = _FIXTURES / "protocol_golden_vectors.json"
RFC8032_VECTORS_PATH = _FIXTURES / "rfc8032_vectors.json"
CONFLICT_VECTORS_PATH = _FIXTURES / "conflict_vectors.json"


@dataclass(frozen=True, slots=True)
class SignatureVector:
    """One signed message: who signed what, and the expected signature."""

    name: str
    private_key_hex: str
    public_key_hex: str
    message_hex: str
    sig_hex: str


@dataclass(frozen=True, slots=True)
class EntityVector:
    """One golden kantaq entity (event or grant) plus its signature vector."""

    name: str
    entity: dict[str, Any]
    private_key_hex: str
    public_key_hex: str
    signing_bytes_hex: str
    sig_hex: str


def load_rfc8032_vectors(path: Path | None = None) -> tuple[SignatureVector, ...]:
    raw = json.loads((path or RFC8032_VECTORS_PATH).read_text())
    vectors = tuple(
        SignatureVector(
            name=entry["name"],
            private_key_hex=entry["private_key_hex"],
            public_key_hex=entry["public_key_hex"],
            message_hex=entry["message_hex"],
            sig_hex=entry["sig_hex"],
        )
        for entry in raw["vectors"]
    )
    if not vectors:
        raise ValueError(f"empty RFC 8032 vector file: {path or RFC8032_VECTORS_PATH}")
    return vectors


def _entity_vectors(raw_entries: list[dict[str, Any]], key: str) -> tuple[EntityVector, ...]:
    return tuple(
        EntityVector(
            name=entry["name"],
            entity=entry[key],
            private_key_hex=entry["private_key_hex"],
            public_key_hex=entry["public_key_hex"],
            signing_bytes_hex=entry["signing_bytes_hex"],
            sig_hex=entry["sig_hex"],
        )
        for entry in raw_entries
    )


def load_protocol_vectors(
    path: Path | None = None,
) -> tuple[tuple[EntityVector, ...], tuple[EntityVector, ...]]:
    """Returns ``(event_vectors, grant_vectors)`` from the golden file."""
    raw = json.loads((path or PROTOCOL_VECTORS_PATH).read_text())
    events = _entity_vectors(raw["events"], "event")
    grants = _entity_vectors(raw["grants"], "grant")
    if not events or not grants:
        raise ValueError(f"golden vector file is incomplete: {path or PROTOCOL_VECTORS_PATH}")
    return events, grants


@dataclass(frozen=True, slots=True)
class ConflictVector:
    """One conflict-merge golden case (MOD-26 §B3): an entity's committed prefix,
    an incoming committed event, and the expected outcome. The SAME file pins
    ``detect_merge`` (Python) and the plpgsql RPC (T2.6) — one decision, one truth."""

    name: str
    committed_prefix: tuple[CommittedEvent, ...]
    incoming: CommittedEvent
    expected_verdict: str
    expected_conflicts: tuple[dict[str, Any], ...]


def _conflict_event(
    entry: dict[str, Any], *, entity_id: str, collection: str, actor_id: str
) -> CommittedEvent:
    revision = int(entry["revision"])
    event = Event(
        event_id=f"evt{revision:023d}",
        collection=collection,
        entity_id=entity_id,
        actor_id=entry.get("actor_id", actor_id),
        actor_seq=int(entry["actor_seq"]),
        op=entry["op"],
        base_rev=entry.get("base_rev"),
        policy_ref=None,
        payload=dict(entry["payload"]),
        sig=None,
    )
    return CommittedEvent(revision=revision, event=event)


def load_conflict_vectors(path: Path | None = None) -> tuple[ConflictVector, ...]:
    """Load the conflict-merge golden vectors (MOD-26 §B3)."""
    raw = json.loads((path or CONFLICT_VECTORS_PATH).read_text())
    entity_id, collection, actor_id = raw["entity_id"], raw["collection"], raw["actor_id"]
    vectors = tuple(
        ConflictVector(
            name=case["name"],
            committed_prefix=tuple(
                _conflict_event(e, entity_id=entity_id, collection=collection, actor_id=actor_id)
                for e in case["committed_prefix"]
            ),
            incoming=_conflict_event(
                case["incoming"], entity_id=entity_id, collection=collection, actor_id=actor_id
            ),
            expected_verdict=case["expected"]["entity_verdict"],
            expected_conflicts=tuple(case["expected"]["conflicts"]),
        )
        for case in raw["cases"]
    )
    if not vectors:
        raise ValueError(f"empty conflict vector file: {path or CONFLICT_VECTORS_PATH}")
    return vectors
